# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e19f8123f1559dd4ee0fd32646b78896eab49970489c5f9c771bd7b11bb12781da0ad2e904c89265a5bab6234ce87ce8647746c8689f9c3afbc2b7fad51e8fd

test:
  secret_key_base: 04b92b0278950213d37408c546dc5baa24ad2602028a444775f0f9e5f2ac66a9de20922d059fd9a1c6cb2e3b7cd5a06dfc68419c9332839de1374a179319aa49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
